language: objective-c
osx_image: xcode7.3
before_install: gem install --no-document cocoapods
install: pod install --repo-update
script:
- set -o pipefail && xcodebuild -workspace Polls.xcworkspace -scheme Polls -sdk iphonesimulator9.3 -destination "platform=iOS Simulator,name=iPhone 5" test | xcpretty -c
