devices([
  'iPhone 6',
  'iPhone 6 Plus',
  'iPhone 5',
  'iPhone 4s',
])

languages([
  'en-US',
])

screenshots_path './screenshots'

clear_previous_screenshots
scheme 'Polls'
project_path '../Polls.xcworkspace'
custom_build_args "OTHER_SWIFT_FLAGS='$(inherited) -DSNAPSHOT'"

